# Generated by Django 5.2.4 on 2025-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_usersessionlog_pagevisitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisitlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
