# Generated by Django 5.2.4 on 2025-07-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_pagevisitlog_device_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisitlog',
            name='device_info',
        ),
    ]
