# Generated by Django 5.2.1 on 2025-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('GFRID', models.IntegerField()),
                ('TS', models.DateTimeField()),
                ('TS_OFF', models.DateTimeField(blank=True, null=True)),
                ('TS_BigInt', models.BigIntegerField()),
                ('TS_OFF_BigInt', models.BigIntegerField(blank=True, null=True)),
                ('jsonFile', models.JSONField()),
                ('last_modified', models.DateTimeField()),
                ('alertNotify_id', models.IntegerField()),
            ],
        ),
    ]
